### ISSUE TITLE
设置外观出错

### ISSUE THREAD

**Issue by wzga** [mnnyang/typecho_theme_mymaterial#1]
Typecho版本 1.1 (17.10.30)
环境 PHP5.6+Nginx+MySql5.6

Warning: Illegal offset type in isset or empty in D:typechoblogvarTypechoWidgetHelperFormElementRadio.php on line 73

建议把音乐播放器的静音功能改成调节音量大小，毕竟有一个暂停了静音意义不大

**Comment by xxyangyoulin** [comment]
感谢反馈，已经解决了报错的问题。
